ALTER TABLE blackbox_rows
  ADD COLUMN image_url text,
  ADD COLUMN brand text,
  ADD COLUMN shipping text,
  ADD COLUMN category text,
  ADD COLUMN bsr int,
  ADD COLUMN upc text,
  ADD COLUMN gtin text,
  ADD COLUMN ean text,
  ADD COLUMN isbn text,
  ADD COLUMN sub_category text,
  ADD COLUMN sub_category_bsr int,
  ADD COLUMN price numeric,
  ADD COLUMN price_trend_90d numeric,
  ADD COLUMN parent_sales int,
  ADD COLUMN asin_sales int,
  ADD COLUMN sales_trend_90d numeric,
  ADD COLUMN parent_revenue numeric,
  ADD COLUMN asin_revenue numeric,
  ADD COLUMN review_count int,
  ADD COLUMN review_rating numeric,
  ADD COLUMN third_party_seller text,
  ADD COLUMN seller_country text,
  ADD COLUMN active_seller_count int,
  ADD COLUMN last_year_sales int,
  ADD COLUMN yoy_sales_percent numeric,
  ADD COLUMN size_tier text,
  ADD COLUMN length numeric,
  ADD COLUMN width numeric,
  ADD COLUMN height numeric,
  ADD COLUMN weight numeric,
  ADD COLUMN storage_fee_jan_sep numeric,
  ADD COLUMN storage_fee_oct_dec numeric,
  ADD COLUMN best_sales_period text,
  ADD COLUMN age_months int,
  ADD COLUMN image_count int,
  ADD COLUMN variant_count int,
  ADD COLUMN sales_review_ratio numeric;

CREATE OR REPLACE VIEW v_blackbox_rows_with_scores AS
SELECT
  r.id AS row_id,
  r.file_id,
  r.row_index,
  r.asin,
  r.url,
  r.title,
  r.image_url,
  r.brand,
  r.shipping,
  r.category,
  r.bsr,
  r.upc,
  r.gtin,
  r.ean,
  r.isbn,
  r.sub_category,
  r.sub_category_bsr,
  r.price,
  r.price_trend_90d,
  r.parent_sales,
  r.asin_sales,
  r.sales_trend_90d,
  r.parent_revenue,
  r.asin_revenue,
  r.review_count,
  r.review_rating,
  r.third_party_seller,
  r.seller_country,
  r.active_seller_count,
  r.last_year_sales,
  r.yoy_sales_percent,
  r.size_tier,
  r.length,
  r.width,
  r.height,
  r.weight,
  r.storage_fee_jan_sep,
  r.storage_fee_oct_dec,
  r.best_sales_period,
  r.age_months,
  r.image_count,
  r.variant_count,
  r.sales_review_ratio,
  r.data,
  s.platform_score,
  s.independent_score,
  s.scored_at
FROM blackbox_rows r
LEFT JOIN product_scores s ON s.row_id = r.id;
