name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install frontend
        working-directory: frontend
        run: npm install
      - name: Lint frontend
        working-directory: frontend
        run: npm run lint
      - name: Test frontend
        working-directory: frontend
        run: npm test
      - name: Build frontend
        working-directory: frontend
        run: npm run build

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install backend
        working-directory: backend
        run: pip install -r requirements.txt
      - name: Lint backend
        working-directory: backend
        run: flake8 .
      - name: Test backend
        working-directory: backend
        run: pytest
